### ISSUE TITLE
No nmap file selected

### ISSUE THREAD

**Issue by Friedwald** [marduc812/vscode-nmap-peek#1]
Hello,
i've tried serval file formats (xml,nmap,txt) but the extension stay's at "No nmap file selected". When i try to refresh i get the error "command nmapViewer.refresh not found". 
Do i need to install something else because i can't find the "fast-xml-parser"  in the Extension Marketplace

Can anyone please help me?
Thank you

![2023-02-28 20_16_42-](https://user-images.githubusercontent.com/96112849/221961830-94151ac9-2fad-4259-8fdd-33ac79700875.png)

**Comment by marduc812** [comment]
Hello @Friedwald,
Can you share the .xml nmap file with me and I can take a look.
If there is something confidential you can replace the IPs and the MAC addresses with a regex replace.

**Comment by Friedwald** [comment]
Hi @marduc812,
thank you for your fast respond. 
Attached are a zip file with two scans one full scan and one scan with port 80 only.


[nmap_xml.zip](https://github.com/marduc812/vscode-nmap-peek/files/10855582/nmap_xml.zip)

**Comment by marduc812** [comment]
Thanks for your scan and issue submission. I fixed the issue and published an update, in a few minutes if you will update the extension it should work.

<img width="457" alt="Screenshot 2023-03-01 at 12 36 58" src="https://user-images.githubusercontent.com/5909985/222129736-7f50cc4c-bcc4-4424-8316-0a8abf1568e9.png">

It was indeed a bug. I wasn't parsing properly the case that there is only one port, which resulted in an object and not an array, to it was returning empty data. 
When you have time, can you confirm that the issue is fixed?

**Comment by Friedwald** [comment]
Great it works. Thank you for your fast respond and fix.
It is such a great and convenient tool while pentesting and taking notes. 
Keep up your great work.

![2023-03-01 17_28_21-Pd53f xml - Visual Studio Code](https://user-images.githubusercontent.com/96112849/222201891-26fe2b5f-ea10-42e1-906d-a10426422fce.png)
![2023-03-01 17_29_36-1 xml - Desktop - Visual Studio Code](https://user-images.githubusercontent.com/96112849/222201908-3f10105b-63b9-48eb-ad66-a7d7b4460c6f.png)
